Task : 3 Car Price Prediction

The price of a car depends on a lot of factors like the goodwill of the brand of the car,
features of the car, horsepower and the mileage it gives and many more. Car price
prediction is one of the major research areas in machine learning.

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
dataset = pd.read_csv("/content/raw.githubusercontent.com_amankharwal_Website-data_master_CarPrice.csv")
dataset.head()

car_ID  symboling                   CarName fueltype aspiration doornumber  \
0       1          3        alfa-romero giulia      gas        std        two   
1       2          3       alfa-romero stelvio      gas        std        two   
2       3          1  alfa-romero Quadrifoglio      gas        std        two   
3       4          2               audi 100 ls      gas        std       four   
4       5          2                audi 100ls      gas        std       four   

       carbody drivewheel enginelocation  wheelbase  ...  enginesize  \
0  convertible        rwd          front       88.6  ...         130   
1  convertible        rwd          front       88.6  ...         130   
2    hatchback        rwd          front       94.5  ...         152   
3        sedan        fwd          front       99.8  ...         109   
4        sedan        4wd          front       99.4  ...         136   

   fuelsystem  boreratio  stroke compressionratio horsepower  peakrpm citympg  \
0        mpfi       3.47    2.68              9.0        111     5000      21   
1        mpfi       3.47    2.68              9.0        111     5000      21   
2        mpfi       2.68    3.47              9.0        154     5000      19   
3        mpfi       3.19    3.40             10.0        102     5500      24   
4        mpfi       3.19    3.40              8.0        115     5500      18   

   highwaympg    price  
0          27  13495.0  
1          27  16500.0  
2          26  16500.0  
3          30  13950.0  
4          22  17450.0  

[5 rows x 26 columns]

In [ ]:
print(dataset.shape)
print(dataset.info()) # dataset not have null value in any feature

(205, 26)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   car_ID            205 non-null    int64  
 1   symboling         205 non-null    int64  
 2   CarName           205 non-null    object 
 3   fueltype          205 non-null    object 
 4   aspiration        205 non-null    object 
 5   doornumber        205 non-null    object 
 6   carbody           205 non-null    object 
 7   drivewheel        205 non-null    object 
 8   enginelocation    205 non-null    object 
 9   wheelbase         205 non-null    float64
 10  carlength         205 non-null    float64
 11  carwidth          205 non-null    float64
 12  carheight         205 non-null    float64
 13  curbweight        205 non-null    int64  
 14  enginetype        205 non-null    object 
 15  cylindernumber    205 non-null    object 
 16  enginesize        205 non-null    

Splitting Input and Output dataset

In [ ]:
input = dataset.drop(["car_ID","price"],axis=1)
output = dataset["price"]

Importent features

In [ ]:
# All feature are important except car_ID

Encoding dataset

In [ ]:
encode_feature = ["CarName","fueltype","aspiration","doornumber","carbody","drivewheel","enginelocation","enginetype","cylindernumber","fuelsystem"]

In [ ]:
from sklearn.preprocessing import LabelEncoder
for i in encode_feature:
  Encode = LabelEncoder()
  input[i]=Encode.fit_transform(input[i])


scalling input data

In [ ]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
input2 = scaler.fit_transform(input)
input2

array([[1.        , 0.01369863, 1.        , ..., 0.34693878, 0.22222222,
        0.28947368],
       [1.        , 0.02054795, 1.        , ..., 0.34693878, 0.22222222,
        0.28947368],
       [0.6       , 0.00684932, 1.        , ..., 0.34693878, 0.16666667,
        0.26315789],
       ...,
       [0.2       , 0.95890411, 1.        , ..., 0.55102041, 0.13888889,
        0.18421053],
       [0.2       , 0.97260274, 0.        , ..., 0.26530612, 0.36111111,
        0.28947368],
       [0.2       , 0.97945205, 1.        , ..., 0.51020408, 0.16666667,
        0.23684211]])

In [ ]:
new_input = pd.DataFrame(input2,columns = input.columns)

In [ ]:
new_input.info() # now all fearutes in float

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 24 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   symboling         205 non-null    float64
 1   CarName           205 non-null    float64
 2   fueltype          205 non-null    float64
 3   aspiration        205 non-null    float64
 4   doornumber        205 non-null    float64
 5   carbody           205 non-null    float64
 6   drivewheel        205 non-null    float64
 7   enginelocation    205 non-null    float64
 8   wheelbase         205 non-null    float64
 9   carlength         205 non-null    float64
 10  carwidth          205 non-null    float64
 11  carheight         205 non-null    float64
 12  curbweight        205 non-null    float64
 13  enginetype        205 non-null    float64
 14  cylindernumber    205 non-null    float64
 15  enginesize        205 non-null    float64
 16  fuelsystem        205 non-null    float64
 1

Seprating data for train and test

In [ ]:
from sklearn.model_selection import train_test_split
x_train , x_test ,y_train,y_test = train_test_split(new_input,output,test_size=0.2,random_state=50)

In [ ]:
x_train.shape,x_test.shape

((164, 24), (41, 24))

importing model

First model = LinearRegression

In [ ]:
from sklearn.linear_model import LinearRegression
model1 = LinearRegression()
model1.fit(x_train,y_train)

LinearRegression()

In [ ]:
pred =model1.predict(x_test)
pred

array([19784.94659217, 13699.5197159 , 17362.72522903, 41103.81595733,
       10053.59813918,  7972.83561957, 16655.52500653, 21492.94370308,
       10470.6569477 ,  7776.42406567, 15257.24293151,  6300.90560579,
       26534.55393194,  9568.51917327,  7593.44972286, 10501.29053856,
       13320.87362223,  9409.43963254, 10886.41579037,  8688.87692893,
        5304.30774183, 15551.84709011,  8369.84740014, 20132.06588413,
        7878.78953023, 18010.52455317, 20011.41041714,  8198.85069453,
        7963.53898707, 13838.85570085, 15690.50285475,  6631.33561873,
        7242.91147867,  4949.93144773,  5593.10431797,  8024.13270052,
       13221.06223735,  6702.33417822,  9164.08087403, 10041.64137344,
       11432.53277846])

To check the accuracy of model

In [ ]:
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(y_test,pred)
np.sqrt(mse)

2545.8183771504214

second model= RandomForestRegression

In [ ]:
from sklearn.ensemble import RandomForestRegressor
model2 = RandomForestRegressor()
model2.fit(x_train,y_train)

RandomForestRegressor()

In [ ]:
pred =model2.predict(x_test)
pred

array([14596.01   , 12264.85   , 18506.75167, 37683.955  , 10125.27   ,
        8238.945  , 15598.6    , 18649.07004,  9684.425  ,  7795.85   ,
       14624.10167,  7726.85   , 29094.665  ,  9336.74   ,  7422.575  ,
        9003.97   , 14498.37   ,  8441.1    ,  9778.38   , 11319.14   ,
        7387.16   , 14797.37167,  6397.335  , 17121.26334,  7118.82   ,
       19249.9    , 17207.51   ,  6760.395  ,  7327.16   ,  9424.83   ,
       15462.47   ,  7665.64   ,  6193.775  , 14550.31   ,  6094.325  ,
        7833.29   ,  9897.17   ,  7027.17   ,  7503.565  ,  8154.56   ,
        9527.34   ])

Evaluating model

In [ ]:
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(y_test,pred)
np.sqrt(mse)

1969.5916698695894

lets check by taking 1 input column

In [ ]:
model2.predict([x_test.loc[100].values]) , y_test[100]

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(


(array([9003.97]), 9549.0)