Importing Library

In [10]:
import numpy as np
import pandas as pd
from sklearn import datasets

Loading Iris dataset from sklearn

In [ ]:
data = datasets.load_iris()
data

Taking Input and Output dataset from data

In [6]:
# In input data 4 features as ['sepal length (cm)','sepal width (cm)','petal length (cm)','petal width (cm)']
X = data["data"]  # Input data

# In output there are 3 classes as ['setosa', 'versicolor', 'virginica'] 
Y = data["target"]  # Output data

In [8]:
# In dataset there is no any null value or any string so we not need to do preprocessing

Splitting data into test and train

In [22]:
from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(X,Y,test_size=0.2,random_state=8)

Importing Models  & Trainig models

First model is KNeighbors

In [23]:
# First model
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier()
model.fit(x_train,y_train)

KNeighborsClassifier()

In [24]:
predict = model.predict(x_test)
predict

array([0, 0, 0, 2, 1, 0, 0, 2, 2, 1, 1, 0, 1, 1, 1, 2, 2, 2, 2, 2, 1, 0,
       1, 1, 1, 0, 2, 0, 0, 2])

Checking Accuracy  & Confusion matrics

In [25]:
from sklearn.metrics import accuracy_score , confusion_matrix
acc = accuracy_score(y_test,predict)
print("Accuracy scored is :",acc)   # Accuracy scored is : 0.9
con = confusion_matrix(y_test,predict)
print("Confusion Matrix is :",con)


Accuracy scored is : 0.9
Confusion Matrix is : [[10  0  0]
 [ 0  8  1]
 [ 0  2  9]]


Second model is SVM

In [39]:
from sklearn.svm import SVC
model1 = SVC(kernel="poly")
model1.fit(x_train,y_train)

SVC(kernel='poly')

In [41]:
predict1 = model1.predict(x_test)
predict1

array([0, 0, 0, 2, 1, 0, 0, 2, 2, 1, 1, 0, 1, 1, 2, 2, 2, 2, 2, 2, 1, 0,
       1, 1, 1, 0, 2, 0, 0, 2])

In [42]:
from sklearn.metrics import accuracy_score , confusion_matrix
acc = accuracy_score(y_test,predict1)
print("Accuracy scored is :",acc)   # Accuracy scored is : 0.9333
con = confusion_matrix(y_test,predict1)
print("Confusion Matrix is :",con)

Accuracy scored is : 0.9333333333333333
Confusion Matrix is : [[10  0  0]
 [ 0  8  1]
 [ 0  1 10]]


Third model is baise

In [44]:
from sklearn.naive_bayes import GaussianNB
model2  = GaussianNB()
model2.fit(x_train,y_train)

GaussianNB()

In [45]:
predict2 = model2.predict(x_test)
predict2

array([0, 0, 0, 2, 1, 0, 0, 2, 2, 1, 1, 0, 1, 1, 1, 2, 2, 2, 2, 2, 2, 0,
       1, 1, 1, 0, 2, 0, 0, 2])

In [46]:
from sklearn.metrics import accuracy_score , confusion_matrix
acc = accuracy_score(y_test,predict2)
print("Accuracy scored is :",acc)   # Accuracy scored is : 0.866
con = confusion_matrix(y_test,predict2)
print("Confusion Matrix is :",con)

Accuracy scored is : 0.8666666666666667
Confusion Matrix is : [[10  0  0]
 [ 0  7  2]
 [ 0  2  9]]


From upper 3 models second model give high accuracy so we choose SVC

classes type

In [28]:
classes = ['setosa', 'versicolor', 'virginica'] 

Creating function for tpye of flower

In [47]:
def flower(sl,sw,pl,pw):
  p = model2.predict([[sl,sw,pl,pw]]) # model.predict gives an array
  return classes[p[0]]

Taking input from user

In [37]:
# sepal length (sl),sepal width (sw)','petal length (pl)','petal width (pw)
sl,sw,pl,pw = map(float,input("Enter length of sepal length (cm),sepal width (cm),petal length (cm),petal width(cm) separated by space : ").split())

Enter length of sepal length (cm),sepal width (cm),petal length (cm),petal width(cm) separated by space : 2 4 5 6


Checking type of flower

In [48]:
flower(sl,sw,pl,pw)

'virginica'