Task 5 : Sales prediction

Sales prediction means predicting how much of a product people will buy based on factors
such as the amount you spend to advertise your product, the segment of people you
advertise for, or the platform you are advertising on about your product.



Typically, a product and service-based business always need their Data Scientist to predict
their future sales with every step they take to manipulate the cost of advertising their
product. So let’s start the task of sales prediction with machine learning using Python

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
dataset = pd.read_csv("/content/Advertising.csv")
dataset.head()

TV  Radio  Newspaper  Sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [ ]:
dataset.info() # there is no null values

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   TV         200 non-null    float64
 1   Radio      200 non-null    float64
 2   Newspaper  200 non-null    float64
 3   Sales      200 non-null    float64
dtypes: float64(4)
memory usage: 6.4 KB


In [ ]:
dataset.describe()

TV       Radio   Newspaper       Sales
count  200.000000  200.000000  200.000000  200.000000
mean   147.042500   23.264000   30.554000   14.022500
std     85.854236   14.846809   21.778621    5.217457
min      0.700000    0.000000    0.300000    1.600000
25%     74.375000    9.975000   12.750000   10.375000
50%    149.750000   22.900000   25.750000   12.900000
75%    218.825000   36.525000   45.100000   17.400000
max    296.400000   49.600000  114.000000   27.000000

In [ ]:
input = dataset.drop(["Sales"],axis =1)
output = dataset.Sales

Scalling data

In [ ]:
from sklearn.preprocessing import RobustScaler
scale = RobustScaler()
input2 =scale.fit_transform(input)

In [ ]:
new_input = pd.DataFrame(input2,columns = input.columns)
new_input

TV     Radio  Newspaper
0    0.556248  0.561205   1.343122
1   -0.728626  0.617702   0.598145
2   -0.917619  0.866290   1.346213
3    0.012115  0.693032   1.012365
4    0.214953 -0.455744   1.009274
..        ...       ...        ...
195 -0.772240 -0.723164  -0.369397
196 -0.384562 -0.677966  -0.545595
197  0.188647 -0.512241  -0.598145
198  0.926618  0.719397   1.250386
199  0.570093 -0.538606  -0.527048

[200 rows x 3 columns]

sepraring data

In [ ]:
from sklearn.model_selection import train_test_split
x_train , x_test , y_train,y_test = train_test_split(new_input,output,test_size =0.2 , random_state=50)

First model : LinearRegression

In [ ]:
from sklearn.linear_model import LinearRegression
model1 = LinearRegression()
model1.fit(x_train,y_train)

LinearRegression()

In [ ]:
pred1 = model1.predict(x_test)
pred1

array([13.7907978 , 14.59424374, 10.55612822,  9.90002998, 10.06819472,
       18.27475851, 15.19128878,  3.44438763, 20.52267528, 11.81767822,
       14.80881144, 12.72461879, 21.13950252, 14.24324005, 15.72214994,
       16.95740482, 10.07042002, 16.62578593,  9.58068105, 12.39525472,
       16.92371559, 10.09265438,  7.99220556, 13.77785614, 21.12007031,
       14.30604103,  7.02891791,  7.429204  , 15.33846692, 13.40314562,
       14.94482091, 10.01155059, 11.92177411, 16.33866375,  6.43543949,
        9.64221908, 13.03688854, 20.4330587 ,  9.03909486, 11.30633312])

Evaluating model

In [ ]:
from sklearn.metrics import mean_squared_error
np.sqrt(mean_squared_error(y_test,pred1))

1.4732770196181142

Second model : RandomForestRegression

In [ ]:
from sklearn.ensemble import RandomForestRegressor
model2  = RandomForestRegressor()
model2.fit(x_train,y_train)

RandomForestRegressor()

In [ ]:
pred2 = model2.predict(x_test)
pred2

array([14.83 , 12.271,  8.341, 11.116, 11.643, 19.052, 13.058,  5.296,
       21.662, 12.479, 12.377, 13.094, 22.292, 14.688, 12.402, 17.443,
       11.493, 15.428, 10.337, 13.091, 15.104, 11.639,  9.392, 11.996,
       20.639, 13.317,  9.587,  9.575, 15.148, 12.069, 14.838, 10.659,
        8.383, 16.076,  9.354, 10.45 , 12.606, 20.028, 10.207, 11.831])

In [ ]:
from sklearn.metrics import mean_squared_error
np.sqrt(mean_squared_error(y_test,pred2))

0.5305734397800195

In [ ]:
model2.predict([[0.556248	,0.561205	,1.343122]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(


array([21.841])